name: Run Bot
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          
      - name: Install dependencies
        run: pip install discord.py selenium webdriver-manager requests Pillow pycountry
        
      - name: Run bot
        run: python passchanger.py ${{ secrets.BOT_TOKEN }}
